# Generated by Django 5.0.6 on 2024-11-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisondata',
            name='user',
        ),
    ]
